carbon_cloud:
  eureka_address: localhost
  mysql_address: localhost
  redis_address: localhost
  mongo_address: localhost
server:
  port: 8005
spring:
  #profiles defined
  profiles:
    active: dev
  application:
    name: Carbon-Mail
eureka:
  instance:
    hostname: carbon-mail
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${carbon_cloud.eureka_address}:8008/eureka/
